### ISSUE TITLE
Cambios sugeridos en LogPaciente

### ISSUE THREAD

**Issue by jfgabriel** [andes/api#15]
Se sugiere un return next(err) en las siguientes líneas

https://github.com/andes/api/blob/5409034af1a67c26e597f686faaf645ad488f6e5/core/log/routes/logPaciente.ts#L34-L38

Si en la app se quiere capturar el error, utilizar Server.get(...., {showMessage: false})

**Comment by jfgabriel** [comment]
@condorpiedra Esto es quedó solucionado en el último pull request?

**Comment by condorpiedra** [comment]
@jfgabriel si en https://github.com/andes/api/pull/18
