### ISSUE TITLE
Codificación de sobreturnos en la Integración

### ISSUE THREAD

**Issue by condorpiedra** [andes/api#282]
Las codificaciones de los sobreturnos que se realizan desde el profesional no se visualizan en las agendas realizadas en Andes.

- [ ] Verificar si se visualiza correctamente si el paciente No Asistió

- [ ] Verificar las codificaciones de Psciología

**Comment by NicoDino** [comment]
Pasó los tests!
@condorpiedra cierro el issue. :smile:
