### ISSUE TITLE
PECAS

### ISSUE THREAD

**Issue by milagrosn** [andes/api#360]
### Comportamiento actual
En los reportes de Pecas : 
_"Tipos de Agenda" no aparecen agendas suspendidas
-"Tipos de turno" no aparecen turnos  "No Asistió", "Suspendidos"

### Resultado esperado 
Debiera aparecer las opciones arriba mencionadas

### Pasos para reproducir el problema 
1. 
2. 
3. 

<!-- Código relevante 

  ```
  // TODO: Código que considere importante incorporar.  
  ``` -->

**Comment by sychus** [comment]
@milagrosn favor mejorar el issue de acuerdo al template ya que no se entiende lo que se espera.

**Comment by milagrosn** [comment]
Resuelto!
