### ISSUE TITLE
Actualización Excel - Pecas

### ISSUE THREAD

**Issue by milagrosn** [andes/api#361]
### Comportamiento actual
* Hay agendas que no se actualiza el estado: (en excel Pendiente de Asistencia, en Andes Pendiente de Auditoría) --> C. S. Progreso, 01/06/2018, Prof. Moreno Marta: las 2 agendas  figuran Pendientes de Auditoria y en Pecas "Pendientes de asistencia"

### Resultado esperado 
* Actualización de estado de las agendas.

### Pasos para reproducir el problema 
1. 
2. 
3. 

<!-- Código relevante 

  ```
  // TODO: Código que considere importante incorporar.  
  ``` -->

**Comment by condorpiedra** [comment]
Fix en PR https://github.com/andes/api/pull/387
