### ISSUE TITLE
Mejoras sugeridas del review relese v3.4.0

### ISSUE THREAD

**Issue by silviroa** [andes/api#389]
### Sugerencias de mejoras
* Cambiar key en permisos: 'puedeEditarCarpeta' por 'editarCarpeta'
* En la búsqueda de historial de turnos del paciente unificar query aggregate para turnos y sobreturnos (turnosController -> getHistorialPaciente). Usar $project con los datos que se desean retornar: turno, turno.id, turno.agenda_id, turno.bloque_id, turno.organizacion, turno.profesionales, turno.paciente.

<!-- Código relevante 

  ```
  // TODO: Código que considere importante incorporar.  
  ``` -->

**Comment by sychus** [comment]
@silviroa sugiero estas cuestiones documentarlas y ponerlas como tareas en el pm. Sólo dejar issues en acá en github

**Comment by NicoDino** [comment]
pasa como propuesta de mejora
