### ISSUE TITLE
Obra Social - Mejora código devolución errores

### ISSUE THREAD

**Issue by lucasgonzalezm** [andes/api#694]
En el archivo `/modules/obraSocial/routes/obraSocial.ts` hay dos errores que se devuelven 
`res.json({ msg: 'Parámetros incorrectos' });`
Deberían devolverse
`return next('Parámetros incorrectos');`
Lo complicado es ver que en la app no se rompa nada al cambiar este tipo de error.

Se debe corregir para que, si ocurriera el error, se muestre de una forma más clara.

![image](https://user-images.githubusercontent.com/18200503/57624803-11abd300-7569-11e9-8e58-668991f1ae68.png)

**Comment by NicoDino** [comment]
@NahirSaddiRTO @kroce  Vi que estamos nosotros en el git blame de estas líneas. Recuerdan si la respuesta de errores se hace así por alguna razón especial?? sería mejor cambiar todas esas respuestas por un next() como dice lucas

**Comment by kroce** [comment]
@NicoDino es cierto...eso habría que cambiarlo...voy a verificar donde se usa y cómo afecta el cambio. No recuerdo porque quedó así.

**Comment by palita1991** [comment]
Se cierra, se subió a producción 25/07/2019 .
