### ISSUE TITLE
MPI - Mejora código devolución error

### ISSUE THREAD

**Issue by lucasgonzalezm** [andes/api#695]
En el archivo `/home/lucas/andes/api/core/mpi/routes/paciente.ts` hay un error que se devuelve
`return res.json(pacienteBuscado);`
Debería devolverse
`return next(pacienteBuscado);`

Lo complicado es ver que en la app no se rompa nada al cambiar este tipo de error.

Se debe corregir para que, si ocurriera el error, se muestre de una forma más clara.
![image](https://user-images.githubusercontent.com/18200503/57625638-a6630080-756a-11e9-9a81-fb26cc106b17.png)

**Comment by NicoDino** [comment]
@lucasgonzalezm Vos hablás del catch anidado dentro del otro try/catch ?? (Te lo señalo en el código)

Si es así, ese catch está capturando solo el error de la fn getObraSocial (que hace unos finds a mongo).
Dado el caso de un error al momento de obtener la obra social, la idea es devolver el paciente ya encontrado con la fn buscarPaciente.
Si ocurriese un error antes de getObraSocial este error sí sería capturado en el otro catch y pasado al handler.

En cuanto al error que encontraste en consola, podemos intentar replicarlo y debuggear para encontrar la causa, probablemente sea otra cosa.

:rocket:

```
// Simple mongodb query by ObjectId --> better performance
router.get('/pacientes/:id', async (req, res, next) => {
    // busca en pacienteAndes y en pacienteMpi
    if (!Auth.check(req, 'mpi:paciente:getbyId')) {
        return next(403);
    }
    if (!(mongoose.Types.ObjectId.isValid(req.params.id))) {
        return next(404);
    }
    try {
        const idPaciente = req.params.id;
        const { paciente: pacienteBuscado } = await controller.buscarPaciente(idPaciente);
        if (pacienteBuscado && pacienteBuscado.documento) {
            let pacienteConOS = pacienteBuscado.toObject({ virtuals: true });
            pacienteConOS.id = pacienteConOS._id;
            try {
                pacienteConOS.financiador = await getObraSocial(pacienteConOS);
                res.json(pacienteConOS);
            } catch (error) {
                return res.json(pacienteBuscado);                   <---------  --------------------         acá
            }
        } else {
            return res.json(pacienteBuscado);
        }
    } catch (err) {
        return next('Paciente no encontrado');
    }

});

```
