### ISSUE TITLE
(MATRICULACIONES) - Datos de matriculación/profesión en turnos nulos

### ISSUE THREAD

**Issue by juuliotero** [andes/api#812]
### Comportamiento actual
* En el listado de turnos no se muestra el número de matrícula ni la profesión

### Resultado esperado 
* Poder visualizar en el listado de turnos número de matrícula y profesión

### Pasos para reproducir el problema 
1. Loguearse en el sistema de matriculaciones
2. Seleccionar una organización del listado donde tenga permisos el usuario
3. Ingresar al listado de turnos
4. Notar que en el listado no figuran el número de matrícula ni la profesión

![image](https://user-images.githubusercontent.com/7090371/67234102-dddbb000-f41a-11e9-8c42-3a1df3dcbca1.png)

**Comment by palita1991** [comment]
Se resuelve en PR https://github.com/andes/api/pull/813
