### ISSUE TITLE
fix(RUP informe PDF): interlineado muy estrecho en textos multilínea

### ISSUE THREAD

**Issue by andrrrl** [andes/api#872]
### Comportamiento actual
* El interlineado de textos largos es muy estrecho, los renglones se enciman.
### Resultado esperado 
* Que el texto tengo un alto de línea normal

### Pasos para reproducir el problema 
1. No está claro, pero sucede con algunos textos descriptivos largos.
![WhatsApp Image 2019-12-16 at 14 27 18](https://user-images.githubusercontent.com/11394455/71020200-a3b92280-20da-11ea-8c83-e6ba460079fc.jpg)
![WhatsApp Image 2019-12-16 at 14 27 19](https://user-images.githubusercontent.com/11394455/71020201-a451b900-20da-11ea-95fd-40921671582e.jpg)

**Comment by palita1991** [comment]
Se resuelve en PR https://github.com/andes/api/pull/898
